// <auto-generated />
using System;
using LearningMassTransit.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearningMassTransit.DataAccess.Migrations
{
    [DbContext(typeof(LaraDbContext))]
    partial class LaraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lara")
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.AtomaireActieState", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Actie")
                        .HasColumnType("text");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("WorkflowId");

                    b.ToTable("AtomaireActieState", "lara");
                });

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("text");

                    b.Property<int>("Actie")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("TicketId");

                    b.ToTable("Ticket", "lara");
                });

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.VoorstellenAdresState", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("WorkflowId");

                    b.ToTable("VoorstellenAdresState", "lara");
                });

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<int>("Actie")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("integer");

                    b.HasKey("WorkflowId");

                    b.ToTable("Workflow", "lara");
                });

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.AtomaireActieState", b =>
                {
                    b.HasOne("LearningMassTransit.Domain.Lara.Workflow", "Workflow")
                        .WithOne("AtomaireActieState")
                        .HasForeignKey("LearningMassTransit.Domain.Lara.AtomaireActieState", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.VoorstellenAdresState", b =>
                {
                    b.HasOne("LearningMassTransit.Domain.Lara.Workflow", "Workflow")
                        .WithOne("VoorstellenAdresState")
                        .HasForeignKey("LearningMassTransit.Domain.Lara.VoorstellenAdresState", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("LearningMassTransit.Domain.Lara.Workflow", b =>
                {
                    b.Navigation("AtomaireActieState");

                    b.Navigation("VoorstellenAdresState");
                });
#pragma warning restore 612, 618
        }
    }
}
